language: node_js
cache:
  directories:
    - node_modules
    - "~/.npm"
node_js:
  - "12"
git:
  depth: 3
script:
  - yarn test
deploy:
  provider: heroku
  skip-cleanup: true
  keep-history: true
  api_key: "d37i6jrDcTfczokJTeQNYGH61JWBTvSZ6IGJxBBKwI/1XM92NhCOTppegu0LkKazSkZZKncrNDKRtzBJu/iAGS4HPJGviXYu+hRRmkxjnbrr0ap/8ufZokeJsqtmmcMBO5VobkqnyRSYnm+iKYUkuSR0UzDhEZTYxRgBeoIDZS8xVzpIwrCHHu7/I4AMDHneq+05cQT/H5rGOXzhyEqNo9kNm703nsj15AnDttfxOFRoALQBXrmh9swCt068X6dgvX6VQjXJeaDJM69Cap4ifyipMN5UU1s8+Rzw3T15IeJaxnByHQGAxfo0S4suGcYRt8SKPc0H8WJmSyqZhcYNMUs+qmHDWErWAryX4ZMBvPa/XTRbKgiWjUKMMOkDmQvTxnl43lkNng3T5cWPVjvf0WAfpi0/Q3uXl+EHQ3t7AL0N4+LOlKmwxOBR+/UUXbGr9wHVQgeg36e/KffjvAJxSJ4QkfUQj57/Xw+jujOzGvuLZ2ZHd7MGyFc5+9upYLafU8B42s/RxmBsOW5CqpAI6+N1DQwz0l20m+dUAklUbRWhlYu1DYEKIH1K3nm/aHo5lyfZaxLfCP9KkNrbWYU+nB+RMFaughifvF/lqF9AdyQILqYIuBxxW1hOA8Lyo9FHAOFUVconqlHV1gv4fW9fUnsyNK5ywcdFVDlhbv19Piw="
  app: mgc-api
  on:
    repo: rubbenpad/employees-management-api
