language: node_js
cache:
  directories:
    - node_modules
    - "~/.npm"
node_js:
  - "12"
git:
  depth: 3
script:
  - yarn test
deploy:
  provider: heroku
  skip-cleanup: true
  keep-history: true
  api_key:
    secure: "MN5NPTzWCpNRilZkqpvmVJl9M5nml9bNgY5HtLYKqegM2Svv0hMpeovmaBkkWC+inM5VHXY2tOQWPRZXhxajGPlp4NrFLfW0Y6kDKHZaKolPeKx3kfRy+ys6DZ3m6HiAHOoEtYaPU64krIAX7F5xViXVpqDp81H4wv6lY8YmYZFSoceuo5ylkNVB+NU2KnjwL8FJKXXBsP/p0LJ9tC8SJZxAm0VCVCO2xqM6oqpC/6wgQGxWP7ti/2y9D9utPlY/aPpEDev45HyLY08yce0OlUNAIjE8emZgJ4sAQC/NlYCGrGkGUknm6vujnRjOoV0/0BfIVTH5n3tNqtUbxQkuoZVPiVHp0eB7q4ja5T8QdqLRAWA46FDIb8LiFBIAtCC8LA81ADbjlhnPXZbMeP/y0pL2zFieuSzaYq9B2WGEZ4d6igh1fdFLQpaYkxRupJ1Lq+WP/SKd3IGiLxVJBodJHkh6My15KUNGQk/BoW+728sjHwFn58Hrjp6TvuyJXR+HEsUH4IZaCvcC4MvNV71GWjd5wt1FR71cV31T2cxjJYpeEZ6RZpIvspArkn9vBK/KHQh2jC07hBxnLDCogNvwOnusc/5kLlFa9lqkaPWyAnx1Z2LETTZMW64Ve1eJZYLqFSLMh0GEUjpWaG188uQ0ww1Eccx6BHPQ4fsgQHQr9MU="
  app: mgc-api
  on:
    repo: rubbenpad/employees-management-api
